spring:
  application:
    name: chiron
  datasource:
    url: jdbc:postgresql://localhost:5432/chiron
    username: postgres
    password: postgres

clinic:
  zone: Europe/Moscow
  slot-step-min: 15

springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000
